################################################################################
### Archive C/C++ build tools (given_fuzzer variant)
################################################################################

FROM ghcr.io/aixcc-finals/base-builder:v1.3.0
COPY --from=multilang-given_fuzzer-builder /opt/llvm-patched /multilang-builder/llvm-patched
COPY --from=multilang-given_fuzzer-builder /usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.fuzzer.a /multilang-builder/libclang_rt.fuzzer.a
COPY --from=multilang-given_fuzzer-builder --chmod=777 /usr/local/bin/compile /multilang-builder/compile
COPY --from=multilang-given_fuzzer-builder --chmod=777 /usr/local/bin/compile_libfuzzer /multilang-builder/compile_libfuzzer
